# This is a simple test action for the build test
name: Build Test

on:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-2022
    steps:
      - name: Get Dependencies from apt
        run: |
          sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-mingw-w64

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"

      - name: Test
        run: |
          go test -v ./...

      - name: Build
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: amd64
        run: |
          go build
